DROP TABLE IF EXISTS sections;
DROP TABLE IF EXISTS courses;

CREATE TABLE courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  number TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  credit_hours INT,
  gen_ed_category TEXT[],
  gen_ed_attribute TEXT[],
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE (subject, number)
);

CREATE TABLE sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  section_number TEXT,
  part_of_term TEXT,
  start_time TIME,
  end_time TIME,
  days_of_week TEXT,
  building TEXT,
  room TEXT,
  instructor TEXT,
  status_code TEXT,
  semester TEXT NOT NULL,
  year INT NOT NULL,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE (course_id, section_number, semester, year)
);

CREATE INDEX idx_courses_gen_ed_category ON courses USING GIN (gen_ed_category);
CREATE INDEX idx_courses_gen_ed_attribute ON courses USING GIN (gen_ed_attribute);
CREATE INDEX idx_courses_subject ON courses(subject);
CREATE INDEX idx_sections_semester_year ON sections(semester, year);
CREATE INDEX idx_sections_course_id ON sections(course_id);

